{"error_args_not_found":"ERROR: The first argument is the bot token not specified","error_auth_fail":"ERROR: Auth error!","db_connection":"Connection to database...","config_version":"0.11"}